### ISSUE TITLE
Disable log in Log implementation

### ISSUE THREAD

**Issue by mxseev** [rust-lang/log#312]
Hi, i am maintainer of [logram](https://github.com/Ralvke/logram). Logram [has log implementation](https://github.com/Ralvke/logram/blob/master/src/lib.rs)
In `Log::log(...)` i send HTTP request, аnd during this request, tokio creates a new log record that goes into `Log::log()`. And so in a circle

Now I have to completely disable the log during the http request
https://github.com/Ralvke/logram/blob/8f4d24afdfd4ba0fc8c2641fc903dee515f4a417/src/lib.rs#L65-L70
But I think this is a bad decision, because there may be problems in multi threaded apps.
How to filter this log records?
Thanks

**Comment by KodrAus** [comment]
Hi @Ralvke :wave:

Hmm, this is a problem with the global nature of `log`, and it doesn't provide any tools out-of-the-box for dealing with `Log` implementations that need to log internally. In general, it's probably good practice not to log at all in implementations of `Log`, but you can't exactly help what `tokio` is going to do several layers underneath you. You can't rely on thread-local-storage in your `Log` implementation to know whether you're within the context of a log to exclude other records because your HTTP request is being handled on an inaccessible threadpool, and can't rely on task-local-storage either because you don't necessarily have an async `Context` to use to fetch it. So right now we're a bit stuck.

For this specific case with the API we have today, maybe the simplest thing you could do is use the [`Record::module_path`](https://docs.rs/log/0.4.6/log/struct.Record.html#method.module_path) method to internally exclude any records that begin with `tokio`, `hyper` or `reqwest` in your `Log` implementation.

In the future I think we'll need to come up with a more robust way to deal with these kinds of cycles.

**Comment by KodrAus** [comment]
Instead of `Record::module_path` you could instead use `Metadata::target` in your implementation of `Log::enabled`.

That'll properly exclude any logs from `tokio` infrastructure instead of giving you a chance to redirect them to somewhere else.
