### ISSUE TITLE
ufmt support

### ISSUE THREAD

**Issue by quininer** [rust-lang/log#332]
The `core::fmt` have a big impact on code size, and @japaric  has developed a smaller and faster alternative [ufmt](https://github.com/japaric/ufmt). Can `log` consider supporting it?

**Comment by KodrAus** [comment]
I imagine the most impact would be in trying to get improvements in size and performance back into `std`, since `ufmt` doesn't appear to provide compatibility with `std::fmt` (since getting at the implementation details of `std::fmt` are unstable) which would affect what can be logged.

We also have to consider the contents of the `kv` module, but it already abstracts away `std::fmt` so wouldn't theoretically be a problem.

**Comment by MathiasKoch** [comment]
I would be very interested in ufmt support :+1:

**Comment by KodrAus** [comment]
An option that’s also since appeared is [`defmt`](https://github.com/knurling-rs/defmt), which is more of an alternative to `log` altogether for very constrained environments. It might be a more appropriate option for users who also need the benefits of `ufmt` beyond any improvements we could possibly make to `std::fmt`.

**Comment by KodrAus** [comment]
At this stage, I think the advice would be to look at something like `defmt` if you need something like `ufmt`.

**Comment by lmbollen** [comment]
I'm sad to see this is issue is closed, as I', currently trying to use `smoltcp`'s loggin infrastructure that utilizes `log` in a `no_std` environment where we use `ufmt`.

I've been attempting to write a custom logger, but have been unable so far because the `core::fmt::Arguments` supplied in the `Record` of `fn log` does not implement `uDisplay`, a trait implemented in `ufmt`.

**Comment by Thomasdezeeuw** [comment]
@lmbollen can `uDisplay` be implemented for `core::fmt::Arguments`? That would bridge the gap not just in the log crate, but it all usage.

**Comment by KodrAus** [comment]
It looks like it should be possible to write an adapter from `std::fmt::Write` to `ufmt::uWrite`, which would let you use the default implementation of `std::fmt::Write::write_arguments` to adapt types implementing `std::fmt` into `ufmt`.
