### ISSUE TITLE
Releases 0.4.9 and 0.4.10 does not available

### ISSUE THREAD

**Issue by MisieEugene** [rust-lang/log#385]
Hi,
The releases 0.4.9 and 0.4.41 are not available on (crates.io)[https://crates.io/crates/log].
Can someone of the team release those, please ?
BR

**Comment by Thomasdezeeuw** [comment]
Both were yanked, see https://github.com/rust-lang/log/issues/369 and https://github.com/rust-lang/log/issues/372.

**Comment by Ophirr33** [comment]
I took a stab at fixing the macro get the tests passing on the `kv_branch`, but there seems to be some issues with going from `$($arg:exp)*` in the `log_impl!` macro back to `$($args:tt)*` in the `__log_format_args!` macro.

**Comment by KodrAus** [comment]
Hey @MisieEugene! :wave:

Yes, unfortunately we had to yank those releases because we had some unexpected compatibility issues with the spongy way the bulk of the log macro is forwarded to `format_args!` that broke consumers.

I think we could work through compatibility better by using a new proc macro.
