### ISSUE TITLE
crate/module specific log levels at compile time

### ISSUE THREAD

**Issue by s3bk** [rust-lang/log#387]
Right now there is a global max_log_level that determines which log events are potentially emitted.
Log implementations are also able to filter log events depending on the crate and module they are emitted from.
However it is not possible to selectively raise the max_log_level of a crate/dependency tree at compile time. Usually this isn't a problem as they have a tiny impact at runtime. How tiny impact has a not so tiny impact when it prevents the compiler from optimizing code and said code happens to be quite hot.

Specifically I ran into this with [pathfinder](https://github.com/servo/pathfinder/) which contains quite a bit of debug! logs, which is not a problem when they compile to nothing.
However I am using pathfinder in an application that still needs debug! logs to actually show up while running fast enough to be used.

I have temporarily "solved" this by wrapping every log! macro in pathfinder in another macro that can be controlled by a feature flag… This obviously isn't a particular good solution.

**Comment by sfackler** [comment]
I'm not sure how this would be implemented.

**Comment by s3bk** [comment]
In the wost case, maybe with a environment variable `RUST_LOG` = `pathfinder=warn` set at compile time? But that might require a proc_macro to parse…

**Comment by hnj2** [comment]
Hey, I've needed exactly this feature, since I need small binaries for an embedded device, but I still want to have logging in some modules for testing purposes.

It can be done by testing for a feature in the `trace!`, `info!`, ..., `error!` macros, but having this feature not be part of the `log` crate, but of the library crate.

I've build an [implementation here](https://github.com/hnj2/log-lib-filter/tree/master).

I think it would be nice to have something like this be part of the log create, instead of needing another create.

This way of doing it would still suffer from the problem, that every library that wants to enable compile-time control of logging for their specific library, would require the library to add features like `log_max_level_*`.

**Comment by KodrAus** [comment]
> In the wost case, maybe with a environment variable RUST_LOG = pathfinder=warn set at compile time? But that might require a proc_macro to parse…

This would require a proc-macro, [but is definitely possible](https://github.com/KodrAus/emit/blob/master/macros/src/filter.rs). I'd love to be able to deprecate the use of Cargo features for max levels in favor of some little filter language in an environment variable.

**Comment by hnj2** [comment]
[Here is an implementation](https://github.com/hnj2/log) that uses an environment variable to filter the log messages at compile time.

Since I needed something that also works on a module level, I've build it to do that.
So you can use a filter like `RUST_LOG_FILTERS="actix_server=Off; actix_server::worker=Trace"`.

[Here are also some tests and examples of how to use it.](https://github.com/hnj2/compile-time-filter-tests).

**Comment by KodrAus** [comment]
Cool work! Thanks for digging into this. Const generics have moved forward somewhat since we last looked at this, but not yet to a point that we could consider using them like this unfortunately. Fine-grained compile-time filtering is a great idea, but I don't think it's something we're considering for `log` itself at this stage. I'd encourage anybody else who's keen to come up with bigger, better, modern `log` macros to explore it externally for now.

I'll go ahead and close this one for now as something that's not on the immediate horizon, but it's still here and discoverable for the future.
