### ISSUE TITLE
How will structured logging interact with nested structures?

### ISSUE THREAD

**Issue by Ophirr33** [rust-lang/log#388]
:wave: I'm looking forward to key value logging being released, and I've attempted to use it directly by skipping the macro. One thing I've run into is that it seems that a `Value` can only be constructed from primitive types. What's the long term vision for how structured logging would look like for things like maps, json objects, structs with serde, etc. ?

I could imagine a json logger that turns something like this:

```rust
let map: HashMap<usize, String> = ...;
let nested_map: HashMap<String, HashMap<String, String>> = ...;
let json_value: serde_json::Value = ...;
let some_struct: Foo = ...;
info!("log all the things!", {
  map: map,
  nested_map: nested_map,
  json_value: json_value,
  foo: some_struct,
});

#[derive(Serialize)]
struct Foo {
  a: usize,
  b: Vec<usize>,
}
```
into the following output:
```
{
  "msg": "log all the things!",
  "map": { ... },
  "nested_map": {
    { ... }
  },
  "json_object": ..., // depends on what kind of value was given
  "foo": {
    "a": 20,
    "b": [1, 2, 3]
  },
  // other logger fields
}
```

**Comment by KodrAus** [comment]
Hi @Ophirr33 :wave:

It's definitely not obvious, because we haven't documented it anywhere yet, but you can actually [capture arbitrary data types in a `Value`](https://docs.rs/log/0.4.8/log/kv/value/struct.Value.html#method.from_sval) and then either [format them back out](https://docs.rs/log/0.4.8/log/kv/value/struct.Value.html#impl-Display) or [serialize them proper](https://docs.rs/log/0.4.8/log/kv/value/struct.Value.html#impl-Value). This is supported in the `kv_unstable_sval` feature using a serialization framework we've written called [`sval`](https://github.com/sval-rs/sval). It's a lot like `serde`, and has [out-of-the-box compatibility with it](https://docs.rs/sval/0.5.1/sval/serde/index.html), but is geared specifically for structured logging and working with trait objects. First-class `serde` support for `Value` is something on the roadmap too.

The way `Value` works is that it abstracts over the way data is captured, so if you capture some type like `serde_json::Value` through `sval`'s compatibility shim then you can either format that `Value` using `Debug` or `Display` (which will approximate what `#[derive(Debug)]` would give you) or you can use `sval` or its `serde` compatibility shim to serialize it as JSON or any other `serde::Serializer` you like. Any `Value` can always be formatted using `std::fmt` or using a serialization framework and retain whatever structure it was captured with.

Does that make sense?

**Comment by KodrAus** [comment]
Just coming in through some triage, I think we've resolved this one as it stands. The docs absolutely need work, but that's something that'll get covered off as we stabilize these APIs. There's some renewed effort going into getting it all across the line.
