### ISSUE TITLE
Compile-time feature for `logger()` to panic if called before `set_logger()`

### ISSUE THREAD

**Issue by anp** [rust-lang/log#416]
Idea: make it possible to have `log!` and other macros panic if called in a binary without a logger.

Motivation: provide a runtime backstop in environments with many binaries to ensure they all have a logger initialized. In $WORK_ENVIRONMENT we have a single list of Cargo features for all the targets in our build which we can use to enforce this as an invariant.

Alternatives: It's possible that a clippy lint or another static analysis solution would work well without changes to the crate but those approaches are vulnerable to false negatives. There's an [existing issue discussing idempotent initialization](https://github.com/rust-lang/log/issues/415) but it's not clear it can be done compatibly with the current ecosystem.

Implementation: I think this would be limited to some `cfg`s [here](https://github.com/rust-lang/log/blob/9a1902dfc69eddc3fd815ba5a63cb7ef21d090db/src/lib.rs#L1432), but would happily be corrected.

**Comment by KodrAus** [comment]
Hmm, as a general feature I'm unsure whether this is likely to be useful except in the case where you know you're going to be emitting log events early in your application's run cycle 🤔 I can appreciate wanting to try get some protection against misconfiguration when you have a lot of entrypoints to consider.

I think if I needed to add some safety checks that logging was initialized in potentially a lot of files I'd try using `syn` to parse all the entrypoint files and use its `visit` API to look for an attribute called `#[log_init]` or something like that which by convention would appear on log statements:

```rust
#[log_init]
my_log_lib::init();
```

and run that in CI. You'd get false positives if the attribute was missing or false negatives if it was randomly applied elsewhere but should give you reasonable confidence without a lot of effort.

I might just be thinking of everything as a `syn`-shaped nail though because I was using it just recently for something else 🙂

**Comment by KodrAus** [comment]
Just coming back through some triage. It's been a while here so I'll go ahead and close this one to keep our open set of issues focused. We haven't gotten past the very earliest stages of any alternative initialization strategy so far. It seems like they all come with upsides and downsides.
