### ISSUE TITLE
Provide a function to check if logger is already set.

### ISSUE THREAD

**Issue by leptonyu** [rust-lang/log#457]
Hi team, can you provide an API to check logger is set?

I need this info to do auto configuration for logger.

**Comment by KodrAus** [comment]
Hi @leptonyu :wave:

The `set_logger` function is fallible, so if it fails then you'll know that a logger beat you to initialization. If you've got a logger you want to set in case none is there then simply calling `set_logger` and ignoring any error would be the way to go. I think that's a preferable approach to an additional check, because the logger is set atomically, so it's possible for you to observe that no logger was set, but for one to have been set before you get a chance to.

Thanks for the suggestion!
