### ISSUE TITLE
implement `Log` on more foreign types

### ISSUE THREAD

**Issue by piegamesde** [rust-lang/log#458]
We already have `impl <T: Log> Log for Box<T>`. It would be cool to have this for more types, for example `Cow<'static, T: Log>`, `Rc` etc.

I'd have to double-check, but this may even be generalizable to `impl <T, R> Log for T where T: Borrow<R>,  R: Log`

**Comment by KodrAus** [comment]
The general impl based on `Borrow` is probably not one we'd want to take on, just because once you have such a broad blanket implementation you end up somewhat painted into a corner with any additional ones you might consider.

I think a bunch of common shared container types would be worthwhile:

- `&'a T: Log + ?Sized`
- `Rc<T: Log>`
- `Arc<T: Log>`

**Comment by piegamesde** [comment]
> just because once you have such a broad blanket implementation you end up somewhat painted into a corner with any additional ones you might consider.

Yes. This is a topic where [impl specialization](https://rust-lang.github.io/rfcs/1210-impl-specialization.html) would be really helpful.

> I think a bunch of common shared container types would be worthwhile

Would you be interested in a PR?

**Comment by KodrAus** [comment]
> Would you be interested in a PR?

Absolutely! 🙏
