### ISSUE TITLE
`match` arms have incompatible types

### ISSUE THREAD

**Issue by 4xoc** [rust-lang/log#462]
When trying to use log macros in a Result<T> match, the match on Err() causes a compile error "error[E0308]: `match` arms have incompatible types". panic! on the other hand works fine. Am I doing something wrong here?

Error message:
```
error[E0308]: `match` arms have incompatible types
  --> examples/usage.rs:14:21
   |
11 |     let f = match f {
   |             ------- `match` arms have incompatible types
12 |         Ok(file) => file,
   |                     ---- this is found to be of type `File`
13 |         // this match failes
14 |         Err(err) => log!(log::Level::Error, "error"),
   |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `File`, found `()`
   |
   = note: this error originates in the macro `log` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0308`.
```

Example code that produces the above error:
```
use log::*;

use std::fs::File;

fn main() {
    let f = File::open("hello.txt");
    let f = match f {
        Ok(file) => file,
        // this match failes
        Err(err) => log!(log::Level::Error, "error"),
    };

    let f = File::open("hello.txt");
    let f = match f {
        Ok(file) => file,
        // using panic! is fine
        Err(error) => panic!("panic"),
    };
}
```
Versions:
rustc 1.55.0 (c8dfcfe04 2021-09-06)
log 0.4.14

**Comment by sfackler** [comment]
Log macros do not panic.

**Comment by 4xoc** [comment]
> Log macros do not panic.

That's not what I have claimed, the panic! was to demonstrate that not all macros fail to compile. All macros of this crate however do, hence the issue.

**Comment by BurntSushi** [comment]
This has nothing to do with macros. Your code isn't expected to compile. Look at your snippet:

```rust
let f = match f {
        Ok(file) => file,
        // this match failes
        Err(err) => log!(log::Level::Error, "error"),
    };
```

What is the type of `f` when the `match` expression hits the `Err` branch? It certainly isn't the same type as if the `Ok` branch is hit.

This works for `panic!` because the type of `panic!` is `!`, which is the [uninhabited type](https://doc.rust-lang.org/std/primitive.never.html) and unifies with anything. (Because anything after a panic in the current thread of execution is unreachable.)

**Comment by 4xoc** [comment]
Oh okay, I didn't know about that. But how would I be able to log such an error of a result?

**Comment by sfackler** [comment]
Other than logging, what do you want to have happen when an error occurs? Should `f` be set to some default value? Should the function return? Should the program exit?

**Comment by golddranks** [comment]
@4xoc The logging itself is not a problem, the `log!` call works just fine, so you can keep that and it should work. The problem is here:
```
let f = match f {
        Ok(file) => file,
        // this match failes
        Err(err) => { 
                log!(log::Level::Error, "error");
                *value that f will be set to comes here*
        }
    };
```

What comes as the `*value that f will be set to comes here*` part? What should the variable `f` to get set as in case of an error? (Or should it set at all? Should the function return? Should there be a panic? Should the program abort?) This is something that is explained in the Book, here's some relevant parts:
https://doc.rust-lang.org/stable/book/ch03-05-control-flow.html
https://doc.rust-lang.org/stable/book/ch06-02-match.html
https://doc.rust-lang.org/stable/book/ch09-00-error-handling.html

**Comment by 4xoc** [comment]
Alright, thanks everyone, I've got it now.
The problem that the Book doesn't explain in particular (or at least I've missed it) is that, without returning/exiting in the Err() match, the compiler complains. The error message is very misleading imho. When I add `std::process::exit(1);` after the log everything works fine.
Anyway, leaving this here in case someone else stumbles upon the same problem.
