### ISSUE TITLE
0.4.15 breaking compatibility for stdlog

### ISSUE THREAD

**Issue by omarabid** [rust-lang/log#493]
slog-stdlog, for some reason, is using __private_api_log function. I understand this has some doc comments warning about not using it, but it might not be the best idea to let people use and not have it bound by semver.

Error Message

```
error[E0061]: this function takes 4 arguments but 3 arguments were supplied
    --> /home/******/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-stdlog-4.1.0/lib.rs:244:9
     |
244  |         log::__private_api_log(format_args!("{}", lazy), level, &(target, info.module(), info.file(), info.line()));
     |         ^^^^^^^^^^^^^^^^^^^^^^ ------------------------  -----  -------------------------------------------------- supplied 3 arguments
     |         |
     |         expected 4 arguments
     |
note: function defined here
    --> /home/******/.cargo/registry/src/github.com-1ecc6299db9ec823/log-0.4.15/src/lib.rs:1576:8
     |
1576 | pub fn __private_api_log(
     |        ^^^^^^^^^^^^^^^^^
```

**Comment by Thomasdezeeuw** [comment]
I think this should be filed with `slog-stdlog`, it's called private for a reason...

**Comment by KodrAus** [comment]
Hey @omarabid :wave:

It's unfortunate that the function is technically publicly reachable, that's just because the `log!` macros need to be able to call it from external code, but it's an implementation detail that isn't meant for use outside of those macros. The `slog-stdlog` project doesn't need to be calling `__private_api_log`, because it only wraps up public functionality anyways.

**Comment by znation** [comment]
Looks like this is being tracked in slog with https://github.com/slog-rs/slog/issues/309
