### ISSUE TITLE
Mutability issues with the `Log` trait

### ISSUE THREAD

**Issue by Geal** [rust-lang/log#51]
Hi,

I would like to implement `Log` for the `syslog` crate, but I cannot do so because the `log` method requires an immutable self: `fn log(&self, record: &LogRecord)`.

In the case of logging to a remote server via TCP, the logger holds an instance of `TcpStream`, which must stay mutable for writing.

Would it be alright to update the trait definition? Or can you suggest a way to bend my code for this?

**Comment by alexcrichton** [comment]
This is actually a crucial aspect of the design of the `Log` trait. Each instance of `Log` can be shared among many threads concurrently (due to the global nature), hence the required `Send` and `Sync` bounds. The only kind of reference that can be shared among threads is `&T`, so for as little overhead as possible the trait signature is `&self` instead of `&mut self`.

If you need a mutable borrow (such as for mutating inner fields), you can use a `Mutex<T>` which will grant you mutable access once locked (and also indicates that your logger is threadsafe)

**Comment by Geal** [comment]
I see, I'll use a Mutex, then. Thanks for your help!
